services:
  mongo:
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - dbnetwork
    restart: always

  backend:
    build: ./backend
    ports:
      - 5050:5050
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - JWT_SECRET=8f43f04b347974580e8816cdc
      - MONGO_URI=mongodb://mongo:27017/travel-tracker
    networks:
      - dbnetwork
    depends_on:
      - mongo
    command: >
      sh -c "npm ci && npm run test"
    restart: always

networks:
  dbnetwork:
    driver: bridge

volumes:
  mongo-data: